
services:
  db:
    image: postgres:15
    container_name: employee_db
    environment:
      POSTGRES_DB: employees_db
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: secure_password_123
    ports:
      - "5432:5432"
    volumes:
      - employee_data:/var/lib/postgresql/data

volumes:
  employee_data:
